name: Update Top Skills

on:
  schedule:
    - cron: "0 0 * * *"  # Runs once daily
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-skills:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Top Skills from GitHub API
        run: |
          curl -s "https://api.github.com/users/frHimanshu/repos?per_page=100" | 
          jq '[.[] | .language] | map(select(. != null)) | group_by(.) | map({(.[0]): length}) | add' > skills.json

      - name: Generate Badge using Shields.io
        run: |
          LANGS=$(jq -r 'to_entries | sort_by(-.value) | .[:5] | map("\(.key) (\(.value))") | join(", ")' skills.json)
          echo "[![Top Skills](https://img.shields.io/badge/Skills-${LANGS// /%20}-blue)](https://github.com/frHimanshu)" > skills_badge.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          mv skills_badge.md README.md
          git add README.md skills.json
          git commit -m "Updated Top Skills Badge"
          git push
